'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IT_Server.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Age_of_Ultron_6087() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Age of Ultron 6087", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Agents_of_Smash_17896() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agents of Smash 17896", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anna_and_Elsa_17760() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anna and Elsa 17760", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avengers_Unite_17664() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avengers Unite 17664", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Baby_Blocks_16301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baby Blocks 16301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batter_Up_Baseball_12659() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batter Up Baseball 12659", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beach_Party_17251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beach Party 17251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Best_Friends_17153() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Best Friends 17153", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Birthday_Celebration_15059() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Birthday Celebration 15059", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blu_and_Family_17879() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blu and Family 17879", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_Baby_Booties_13412() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue Baby Booties 13412", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Brave_Merida_and_Angus_15394() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brave Merida and Angus 15394", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cars_2_World_Grand_Prix_14452() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cars 2 World Grand Prix 14452", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Championship_Belt_6353() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Championship Belt 6353", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Charm_Caucasian_17859() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charm Caucasian 17859", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Charm_Hispanic_18103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charm Hispanic 18103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cinderella_Transfrom_18699() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cinderella Transfrom 18699", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Coal_Car_14142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coal Car 14142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dinosaur_Pals_11825() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dinosaur Pals 11825", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Doc_and_Lambie_17801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc and Lambie 17801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drift_6088() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drift 6088", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Extra_Fruit_Cake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Extra Fruit Cake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Favorite_High_Heels_17158() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favorite High Heels 17158", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Felling_Boovie_18476() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Felling Boovie 18476", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frame_and_Skullette_17042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame and Skullette 17042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Garden_Royalty_14114() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Garden Royalty 14114", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gil__Molly_and_Gang_17791() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gil, Molly and Gang 17791", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Happily_Ever_After_18035() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Happily Ever After 18035", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Horses_16449() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horses 16449", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jungle_18078() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jungle 18078", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jungle_Buddies_12377() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jungle Buddies 12377", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Just_Yelp_for_Help_6089() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Just Yelp for Help 6089", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Krabby_Patty_6086() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Krabby Patty 6086", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Light_Up_Eyes_18029() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Light Up Eyes 18029", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lion_King_Baby_Simba_17759() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lion King Baby Simba 17759", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Luau_Party_15015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luau Party 15015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Milano_18243() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Milano 18243", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minnie_Hat_Box_16754() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minnie Hat Box 16754", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nemo_and_Squirt_16135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nemo and Squirt 16135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Tail_for_Eeyore_17088() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Tail for Eeyore 17088", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pink_Baby_Booties_13405() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pink Baby Booties 13405", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pirates_Treasure_Hunt_14834() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pirates Treasure Hunt 14834", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Planes_2_Air_Attack_Team_18255() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Planes 2 Air Attack Team 18255", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Queen_Crown_and_Scepter_14213() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen Crown and Scepter 14213", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ranchologo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ranchologo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rapunzel_and_Castle_17902() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rapunzel and Castle 17902", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Red_Zord_5002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red Zord 5002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Regural_Fruit_Cake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Regural Fruit Cake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Safari_Babies_34514() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safari Babies 34514", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Soccer_Kick_Off_Boys_14236() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soccer Kick Off Boys 14236", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sofia_and_Castle_17665() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sofia and Castle 17665", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Special_Delibery_Stork_10218() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Special Delibery Stork 10218", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sponge_Bob_14917() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sponge Bob 14917", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Students_Micke_and_Sulley_17312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Students Micke and Sulley 17312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property The_Little_Mermaid_17047() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("The Little Mermaid 17047", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property The_Princes_and_The_Frog_17223() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("The Princes and The Frog 17223", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tinker_Bell_and_Periwnkle_16927() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinker Bell and Periwnkle 16927", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tinker_Bell_in_Flower_13162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinker Bell in Flower 13162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Touchdown_Football_12660() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Touchdown Football 12660", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Turtles_to_Action_17051() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turtles to Action 17051", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_Spinner_17141() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web Spinner 17141", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Winnie_the_Pooh_Welcome_Baby_17183() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Winnie the Pooh Welcome Baby 17183", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Woody__Buzz_and_Aliens_18083() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Woody, Buzz and Aliens 18083", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Yo_Ho_Way_to_Go_15952() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yo Ho Way to Go 15952", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
